services:
  postgres_real_estate_listing:
    image: postgres:alpine
    container_name: postgres_real_estate_listing
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_real_estate_listing:
    image: redis:alpine
    container_name: redis_real_estate_listing
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

networks:
  default:
    name: real_estate_listing

volumes:
  postgres_data:
  redis_data:
