services:
  postgres_real_estate_listing_test:
    image: postgres:alpine
    container_name: postgres_real_estate_listing_test
    restart: 'no'
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5444:5432' # Different port to avoid conflict with the development environment
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5

  redis_real_estate_listing_test:
    image: redis:alpine
    container_name: redis_real_estate_listing_test
    ports:
      - '6380:6379' # Different port to avoid conflict with the development environment
    volumes:
      - redis_data_test:/data

networks:
  default:
    name: real_estate_listing_test

volumes:
  postgres_data_test:
  redis_data_test:
